# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "ca-central-1"
  allowed_account_ids = ["891377066226"]
  
  default_tags {
    tags = {
      Environment = "dev"
      ManagedBy   = "Terragrunt"
    }
  }
}
