%%{init: {'theme':'neutral'}}%%
graph TB
    RelyingParty[Relying Party]
    WebBrowser["User Agent (Web Browser)"]

    subgraph AWS["CDS AWS Cloud ca-central-1"]
        subgraph GC Sign in Backend
            subgraph "VPC"
                subgraph PublicSubnet["Public Subnet"]
                    ALB["Application Load Balancer<br/>(routes backend API traffic)"]
                end

                subgraph PrivateSubnet["Private Subnet"]
                    subgraph ECS["ECS Cluster (FARGATE)"]
                        subgraph BackendContainer["Backend Container"]
                            APIBackend["GC Sign in Backend API (FastAPI)"]
                            APIClient["IBM Verify API Client"]
                        end
                    end
                end
            end
        end

        subgraph GC Sign in Frontend
            CloudFront["CloudFront<br/>(serves custom Web assets)"]
            subgraph S3[S3 Bucket]
                GCSigninFrontEnd[GC Sign in Frontend Web assets]
            end
        end

        CloudWatch[CloudWatch]
        SecretsManager[Secrets Manager]
        ECR["ECR"]
        Route53["Route 53 (DNS)"]
        WAF[AWS WAF]
    end

    subgraph IBMVerify["IBM Cloud (canada)"]
        IBMVerifyFeatures["<strong>IBM VERIFY SaaS</strong><br/><br/>OIDC Services<br/>Monitoring and Repoting<br/>APIs<br/>MFA Enroll/Verify<br/>Identity Store"]
    end

    subgraph Azure["CDS Azure Cloud (canada)"]
        Sentinel["Microsoft Sentinel (CDS)"]
    end
    
    

    %% Connections
    WebBrowser-->|"Access<br/>HTTPS"| RelyingParty
    WebBrowser ------->|"HTTPS<br/>Sign in / Sign up / Manage"| AWS
    RelyingParty-->|"OIDC endpoints<br/>HTTPS"| IBMVerify
    RelyingParty-->|"Redirect (authorize)"| WebBrowser
    CloudFront -->|Static Content| S3
    WAF -.->|Protect| ALB
    WAF -.->|Protect| CloudFront
    PublicSubnet -->|API Requests| PrivateSubnet
    APIBackend-->|Uses| APIClient
    APIClient -->|HTTPS| IBMVerify
    APIClient -->|Secrets| SecretsManager

    %% Monitoring
    WAF -.->|Logs| CloudWatch
    APIBackend -.->|Logs| CloudWatch
    CloudWatch -->|Logs| Sentinel
    IBMVerify -->|Logs| Sentinel

    %% Styling
    classDef aws fill:#FF9900,stroke:#232F3E,color:white;
    classDef gcsignin fill:#FF5733,stroke:#232F3E,color:white;
    classDef ibm fill:#3B76e2,stroke:#232F3E,color:white;
    classDef ibmchild fill:#1B46C2,stroke:#232F3E,color:white;
    classDef users fill:#6BBE49,stroke:#232F3E,color:white;
    classDef rp fill:#8B8000,stroke:#232F3E,color:white;
    classDef azure fill:#12267d,stroke:#23F3E,color:white;
    classDef docker fill:#EEEEEE,stroke:#23F3E,color:grey;

    class Route53,CloudFront,ALB,WAF,CFWAF,ECS,ECR,CloudWatch,SecretsManager,WAFLogs,S3 aws;
    class IBMVerifyFeatures ibm;
    class WebBrowser users;
    class RelyingParty rp;
    class GCSigninFrontEnd,APIBackend,APIClient gcsignin;
    class Sentinel azure;
    class BackendContainer docker;