%%{init: {'theme':'neutral'}}%%
graph TB
    subgraph "AWS Cloud - GC Sign In (Region: ca-central-1)"
        subgraph "VPC"
            subgraph "Public Subnet"
                ALB[Application Load Balancer]
                WAF[AWS WAF]
            end

            subgraph "Private Subnet"
                subgraph "ECS Cluster"
                    subgraph "Backend Container"
                        APIProxy["API Proxy (FastAPI)"]
                        APIClient["IBM Verify API Client"]
                    end
                end

            end
        end

        CloudWatch[CloudWatch]
        SecretsManager[Secrets Manager]

        subgraph "CloudFront Edge"
            CloudFront[CloudFront]
            CFWAF[AWS WAF]
        end

        Route53["Route 53 (DNS)"]
        
        S3[S3 Bucket<br/>Front-end Web assets]
    end

    subgraph "IBM Cloud (Canada)"
        subgraph IBMVerify["IBM Verify SaaS"]
            IBMVerifyAPI["IBM Verify APIs"]
            IBMIDaaS["OIDC Services"]
            IBMMonitoringReporting["Monitoring and Reporting"]
            IBMIDStore["Identity Store"]
            IBMMFA["MFA Enroll and Verify"]
        end
    end

    RelyingParty[Relying Party]
    WebBrowser["Users (Web Browser)"]
    Sentinel["Microsoft Sentinel"]

    %% Connections
    WebBrowser -->|HTTPS| CloudFront
    WebBrowser -->|"API Calls<br/>HTTPS"| ALB
    WebBrowser -->|"OIDC endpoints<br/>HTTPS"| IBMVerify
    CloudFront -->|Static Content| S3
    WAF -.->|Protect| ALB
    CFWAF -.->|Protect| CloudFront
    ALB -->|API Requests| APIProxy
    APIClient -->|Signup+Signin+MFA+Profile HTTPS| IBMVerify
    APIClient -->|Secrets| SecretsManager
    RelyingParty-->|"OIDC endpoints<br/>HTTPS"| IBMVerify
    RelyingParty-->|"Redirect (authorize)<br/>HTTPS"| WebBrowser
    WebBrowser-->|"Redirect (callback)<br/>HTTPS"| RelyingParty
    APIProxy-->|Uses| APIClient

    %% Monitoring
    WAF -.->|Logs| CloudWatch
    APIProxy -.->|Logs| CloudWatch
    CloudWatch -->|Logs| Sentinel
    IBMMonitoringReporting -->|Logs| Sentinel

    %% Styling
    classDef aws fill:#FF9900,stroke:#232F3E,color:white;
    classDef gcsignin fill:#FF5733,stroke:#232F3E,color:white;
    classDef ibm fill:#3B76e2,stroke:#232F3E,color:white;
    classDef ibmchild fill:#1B46C2,stroke:#232F3E,color:white;
    classDef users fill:#6BBE49,stroke:#232F3E,color:white;

    class Route53,CloudFront,ALB,WAF,CFWAF,ECS,CloudWatch,SecretsManager,WAFLogs,S3 aws;
    class IBMVerify ibm;
    class IBMVerifyAPI,IBMIDaaS,IBMMonitoringReporting,IBMIDStore,IBMMFA ibmchild;
    class RelyingParty,WebBrowser users;
    class GCSigninFrontEnd,APIProxy,APIClient gcsignin;