%%{init: {'theme':'neutral'}}%%
graph TB
    subgraph AWS["CDS AWS Cloud ca-central-1"]
        subgraph "VPC"
            subgraph PublicSubnet["Public Subnet"]
                ALB["Application Load Balancer<br/>(routes backend API traffic)"]
            end

            subgraph "Private Subnet"
                subgraph ECS["ECS Cluster"]
                    subgraph "Backend Container"
                        APIBackend["GC Sign in Backend API (FastAPI)"]
                        APIClient["IBM Verify API Client"]
                    end
                end

            end
        end

        CloudWatch[CloudWatch]
        SecretsManager[Secrets Manager]
        CloudFront["CloudFront<br/>(serves custom Web assets)"]
        ECR["ECR"]
        Route53["Route 53 (DNS)"]
        subgraph S3[S3 Bucket]
            GCSigninFrontEnd[GC Sign in Frontend Web assets]
        end
        WAF[AWS WAF]

        
    end

    subgraph GitHub
        subgraph CDSGitHub["CDS GitHub Org"]
            subgraph GitHubActions["GC Sign in GitHub actions"]
                GitHubAWSOIDCClient["Code Deploy<br/>(AWS OIDC Client)"]
                GitHubCodeCoverage["Code Coverage"]
                GitHubCodeScanning["Code Scanning"]
            end
            GitHubSecrets["GitHub Secrets"]
            subgraph GCSigninCodeRepo["GC Sign in Code Repo"]
                ApplicationCode["Application Code"]
                InfrastructureCode["Infrastructure Code"]
            end
        end
    end

    subgraph IBMVerify["IBM Cloud (canada)"]
        IBMVerifyFeatures["<strong>IBM VERIFY SaaS</strong><br/><br/>OIDC Services<br/>Monitoring and Repoting<br/>APIs<br/>MFA Enroll/Verify<br/>Identity Store"]
    end

    RelyingParty[Relying Party]
    WebBrowser["User Agent (Web Browser)"]

    subgraph Azure["CDS Azure Cloud (canada)"]
        Sentinel["Microsoft Sentinel (CDS)"]
    end
    
    %% Connections
    GitHubAWSOIDCClient-->|Deploy| AWS
    GCSigninCodeRepo-->GitHubActions

    WebBrowser -->|"HTTPS"| AWS
    CloudFront -->|Static Content| S3
    WAF -.->|Protect| ALB
    WAF -.->|Protect| CloudFront
    ALB -->|API Requests| APIBackend
    APIClient -->|HTTPS| IBMVerify
    APIClient -->|Secrets| SecretsManager
    RelyingParty-->|"OIDC endpoints<br/>HTTPS"| IBMVerify
    WebBrowser-->|"Access<br/>HTTPS"| RelyingParty
    APIBackend-->|Uses| APIClient

    %% Monitoring
    WAF -.->|Logs| CloudWatch
    APIBackend -.->|Logs| CloudWatch
    CloudWatch -->|Logs| Sentinel
    IBMVerify -->|Logs| Sentinel

    %% Styling
    classDef aws fill:#FF9900,stroke:#232F3E,color:white;
    classDef gcsignin fill:#FF5733,stroke:#232F3E,color:white;
    classDef ibm fill:#3B76e2,stroke:#232F3E,color:white;
    classDef ibmchild fill:#1B46C2,stroke:#232F3E,color:white;
    classDef users fill:#6BBE49,stroke:#232F3E,color:white;
    classDef rp fill:#8B8000,stroke:#232F3E,color:white;
    classDef github fill:#92C3D2,stroke:#23F3E,color:white;
    classDef githubchild fill:#6299B2,stroke:#23F3E,color:white;
    classDef azure fill:#12267d,stroke:#23F3E,color:white;

    class Route53,CloudFront,ALB,WAF,CFWAF,ECS,ECR,CloudWatch,SecretsManager,WAFLogs,S3 aws;
    class IBMVerifyFeatures ibm;
    class WebBrowser users;
    class RelyingParty rp;
    class GCSigninFrontEnd,APIBackend,APIClient gcsignin;
    class GitHubActions,GCSigninCodeRepo,GitHubSecrets github;
    class GitHubAWSOIDCClient,ApplicationCode,InfrastructureCode,GitHubCodeCoverage,GitHubCodeScanning githubchild;
    class Sentinel azure;