import ManageDashboard from "../components/Manage/ManageDashboard.jsx";
import ProfileHome from "../components/Manage/ProfileHome";
import config from '../config';
export const AVAILABLE_LANGUAGES = { en: 'en', fr: 'fr' };
export const PROFILE_LANGUAGES = {
    en: 'en-ca',
    fr: 'fr-ca',
};
export const LANGUAGE_DISPLAY_NAMES = {
    'en-ca': 'English',
    'fr-ca': 'French',
};
const securitySettings = '/securitysettings';
export const NAVIGATION_LINKS = {
    signUp: '/signup',
    verifyEmail: '/signup/verification/email',
    password: `${securitySettings}/password`,
    twoStepVerification: '/signup/verificationsetup',
    verification: '/verification',
    coreProfile: '/signup/profile',
    privacy: '/signup/privacy',
    home: '/',
    verificationSelection: '/signin/selectverification',
    manage: '/',
    ProfileNameEdit: '/ProfileNameEdit',
    profileHome: '/profilehome',
    checkYourEmail: '/checkyouremail',
    completeTwoStepVerification: '/completetwostepverification',
    firstVerifyItsYou: '/firstverifyitsyou',
    enterNewEmail: '/enternewemail',
    profileYouMayUpdateName: '/profileyoumayupdatename',
    areYouSureEditYourName: '/areYouSureEditYourName',
    areYouSureUpdateContactNumber: '/areYouSureUpdateContactNumber',
    enterNewPhoneNumber: '/enterNewPhoneNumber',
    youMayUpdateEmailAtOtherPlaces: '/youMayUpdateEmailAtOtherPlaces',
    areYouSureUpdateYourEmail: '/areYouSureUpdateYourEmail',
    securitySettings: securitySettings,
    editLanguagePreferences: '/editlanguage',
    areYouSureEditYourLanguage: '/areYouSureEditYourLanguage',
    profileYouMayUpdateLanguage: '/profileyoumayupdatelanguage'

};
export const OIDC_REDIRECT = {
    login: `${config.apiUrl}/v1/auth/login`,
    reauth: `${config.apiUrl}/v1/auth/reauth`,
}

export const CONTEXT_ACTIONS = {
    signUp: 'SIGN_UP',
    signIn: 'SIGN_IN',
    logOut: 'LOG_OUT',
    signin_success: 'SIGNIN_SUCCESS',
    signin_failure: 'SIGNIN_FAILURE',
    clone_profile: 'CLONE_PROFILE',
    clear_edit_profile: 'CLEAR_EDIT_PROFILE',
    update_cloned_profile: 'UPDATED_CLONE_PROFILE',
    update_profile: 'UPDATE_PROFILE',
    updated_profile_success: 'UPDATE_PROFILE_SUCCESS',
    set_original_language_before_edit: 'SET_ORIGINAL_LANGUAGE_BEFORE_EDIT',
    cancel_profile_editing: 'CANCEL_PROFILE_EDITING',
    set_language: 'SET_LANGUAGE',
    set_relying_party_data: 'SET_RELYING_PARTY_DATA',
    set_authenticated_pages: 'SET_AUTHENTICATED_PAGES',
};

export const FLOW_TYPES = {
    signUp: "signup",
    signIn: "signin",
    sms: "smsotp",
    voice: "voiceotp",
    email: "email",
    dashboard: "dashboard",
    profile: "profile",
    manage: "manage"
}

export const LINK_SUBMIT_TYPES = {
    useNewVerification: 'useNewVerification',
    requestNewCode: 'requestNewCode'
}

export const FORM_FIELDS = ['email', 'language', 'verificationCode', 'password', 'phone', 'verificationType', 'firstName', 'lastName'];

export const PAGES = {
    signup: 'SignUpEmail',
    verification: 'Verification',
    privacy: 'Privacy',
    verificationSetUp: 'VerificationSetUp',
    coreProfile: 'CreateCoreProfile',
    updatePassword: 'UpdatePassword',
    home: 'Home',
    error: 'Error',
    verificationSelection: 'VerificationSelection',
    manageDashboard: 'ManageDashboard',
    ProfileHome: 'ProfileHome',
    CheckYourEmail: 'CheckYourEmail',
    CompleteTwoStepVerification: 'CompleteTwoStepVerification',
    FirstVerifyItsYou: 'FirstVerifyItsYou',
    EnterNewEmail: 'EnterNewEmail',
    profileYouMayUpdateName: 'ProfileYouMayUpdateName',
    areYouSureEditYourName: 'AreYouSureEditYourName',
    ProfileNameEdit: 'ProfileNameEdit',
    areYouSureUpdateContactNumber: 'AreYouSureUpdateContactNumber',
    enterNewPhoneNumber: 'EnterNewPhoneNumber',
    youMayUpdateEmailAtOtherPlaces: 'YouMayUpdateEmailAtOtherPlaces',
    areYouSureUpdateYourEmail: 'AreYouSureUpdateYourEmail',
    securitySettings: 'SecuritySettings',
    editLanguagePreferences: 'EditLanguagePreferences',
    areYouSureEditYourLanguage: 'AreYouSureEditYourLanguage',
    profileYouMayUpdateLanguage: 'ProfileYouMayUpdateLanguage',
}

export const FOOTERS = {
    default: {
        en: '{ "About GC Sign in": "https://gc-signin.cdssandbox.xyz/en/", "Help": "https://gc-signin.cdssandbox.xyz/en/", "Terms": "https://gc-signin.cdssandbox.xyz/en/" }',
        fr: '{ "À propos de Connexion GC": "https://gc-signin.cdssandbox.xyz/en/", "Aide": "https://gc-signin.cdssandbox.xyz/fr/", "Avis": "https://gc-signin.cdssandbox.xyz/en/" }'
    }
}

export const SERVICES = [
    {
        id: 1,
        title: 'Parks Canada Reservations',
        description: '',
        url: '#'
    }
];

export const SUBMIT_END_POINTS = {
    requestPasswordPolicy: '/v1/password/policy',
    create: '/v1/users/create',
    createCoreProfile: '/v1/users/createcoreprofile',
    transientOtpVerify: '/v1/otp/transient_otp/verify',
    transientOtpSend: '/v1/otp/transient_otp/send',
    login: '/v1/otp/users/login',
    otpVerify: '/v1/otp/otp/verify',
    otpSend: '/v1/otp/otp/send',
    profile: '/v1/users/profile',
    rp_info: '/v1/users/rp_info',
    users: '/v1/users'
}


export const GA_CATEGORIES = {
    pageView: "pageview",
    onboarding: "sign_up_flow",
    signIn: "sign_in",
}

export const GA_ACTIONS = {
    clickFirstTimeGc: "Clicked FirstTimeGC -> Privacy",
}

export const GA_LABELS = {
    button: "Button",
    link: "Link",
    text: "Text",
    input: "Input",
    email: "Email",
}

export const countryMapping = {
    countries: ['ar',
        'at',
        'au',
        'by',
        'be',
        'br',
        'bg',
        'ca',
        'cl',
        'co',
        'cr',
        'hr',
        'dk',
        'do',
        'ec',
        'eg',
        'ee',
        'ei',
        'fi',
        'fr',
        'de',
        'gr',
        'gp',
        'gt',
        'gg',
        'hk',
        'hu',
        'is',
        'in',
        'id',
        'ie',
        'im',
        'il',
        'it',
        'jm',
        'jp',
        'je',
        'ke',
        'lt',
        'lu',
        'mk',
        'my',
        'mx',
        'ma',
        'nl',
        'nz',
        'ng',
        'no',
        'om',
        'pk',
        'pa',
        'pe',
        'ph',
        'pl',
        'pt',
        'pr',
        'qa',
        'ro',
        'ru',
        'sa',
        'sg',
        'sk',
        'za',
        'kr',
        'es',
        'lk',
        'se',
        'ch',
        'tw',
        'th',
        'tt',
        'tr',
        'ua',
        'gb',
        'us',
        'uy',
        'uz',
        've',
        'vn'
    ],
    localization: {
        'gg': 'Guernsey',
        'im': 'Isle of Mann',
        'je': 'Jersey',
        my: 'Malasia'
    },
    frLocalization: {
        "af": "Afghanistan",
        "za": "Afrique du Sud",
        "al": "Albanie",
        "dz": "Algérie",
        "de": "Allemagne",
        "ad": "Andorre",
        "ao": "Angola",
        "ai": "Anguilla",
        "aq": "Antarctique",
        "ag": "Antigua-et-Barbuda",
        "sa": "Arabie saoudite",
        "ar": "Argentine",
        "am": "Arménie",
        "aw": "Aruba",
        "au": "Australie",
        "at": "Autriche",
        "az": "Azerbaïdjan",
        "bs": "Bahamas",
        "bh": "Bahreïn",
        "bd": "Bangladesh",
        "bb": "Barbade",
        "be": "Belgique",
        "bz": "Belize",
        "bj": "Bénin",
        "bm": "Bermudes",
        "bt": "Bhoutan",
        "by": "Biélorussie",
        "bo": "Bolivie",
        "ba": "Bosnie-Herzégovine",
        "bw": "Botswana",
        "br": "Brésil",
        "bn": "Brunéi Darussalam",
        "bg": "Bulgarie",
        "bf": "Burkina Faso",
        "bi": "Burundi",
        "kh": "Cambodge",
        "cm": "Cameroun",
        "ca": "Canada",
        "cv": "Cap-Vert",
        "ea": "Ceuta et Melilla",
        "cl": "Chili",
        "cn": "Chine",
        "cy": "Chypre",
        "co": "Colombie",
        "km": "Comores",
        "cg": "Congo-Brazzaville",
        "cd": "Congo-Kinshasa",
        "kp": "Corée du Nord",
        "kr": "Corée du Sud",
        "cr": "Costa Rica",
        "ci": "Côte d’Ivoire",
        "hr": "Croatie",
        "cu": "Cuba",
        "cw": "Curaçao",
        "dk": "Danemark",
        "dg": "Diego Garcia",
        "dj": "Djibouti",
        "dm": "Dominique",
        "eg": "Égypte",
        "ae": "Émirats arabes unis",
        "ec": "Équateur",
        "er": "Érythrée",
        "es": "Espagne",
        "ee": "Estonie",
        "sz": "Eswatini",
        "va": "État de la Cité du Vatican",
        "fm": "États fédérés de Micronésie",
        "us": "États-Unis",
        "et": "Éthiopie",
        "fj": "Fidji",
        "fi": "Finlande",
        "fr": "France",
        "ga": "Gabon",
        "gm": "Gambie",
        "ge": "Géorgie",
        "gs": "Géorgie du Sud et îles Sandwich du Sud",
        "gh": "Ghana",
        "gi": "Gibraltar",
        "gr": "Grèce",
        "gd": "Grenade",
        "gl": "Groenland",
        "gp": "Guadeloupe",
        "gu": "Guam",
        "gt": "Guatemala",
        "gg": "Guernesey",
        "gn": "Guinée",
        "gq": "Guinée équatoriale",
        "gw": "Guinée-Bissau",
        "gy": "Guyana",
        "gf": "Guyane française",
        "ht": "Haïti",
        "hn": "Honduras",
        "hu": "Hongrie",
        "cx": "Île Christmas",
        "ac": "Île de l’Ascension",
        "im": "Île de Man",
        "nf": "Île Norfolk",
        "ax": "Îles Åland",
        "ky": "Îles Caïmans",
        "ic": "Îles Canaries",
        "cc": "Îles Cocos",
        "ck": "Îles Cook",
        "fo": "Îles Féroé",
        "fk": "Îles Malouines",
        "mp": "Îles Mariannes du Nord",
        "mh": "Îles Marshall",
        "um": "Îles mineures éloignées des États-Unis",
        "pn": "Îles Pitcairn",
        "sb": "Îles Salomon",
        "tc": "Îles Turques-et-Caïques",
        "vg": "Îles Vierges britanniques",
        "vi": "Îles Vierges des États-Unis",
        "in": "Inde",
        "id": "Indonésie",
        "iq": "Irak",
        "ir": "Iran",
        "ie": "Irlande",
        "is": "Islande",
        "il": "Israël",
        "it": "Italie",
        "jm": "Jamaïque",
        "jp": "Japon",
        "je": "Jersey",
        "jo": "Jordanie",
        "kz": "Kazakhstan",
        "ke": "Kenya",
        "kg": "Kirghizistan",
        "ki": "Kiribati",
        "xk": "Kosovo",
        "kw": "Koweït",
        "re": "La Réunion",
        "la": "Laos",
        "ls": "Lesotho",
        "lv": "Lettonie",
        "lb": "Liban",
        "lr": "Libéria",
        "ly": "Libye",
        "li": "Liechtenstein",
        "lt": "Lituanie",
        "lu": "Luxembourg",
        "mk": "Macédoine",
        "mg": "Madagascar",
        "my": "Malaisie",
        "mw": "Malawi",
        "mv": "Maldives",
        "ml": "Mali",
        "mt": "Malte",
        "ma": "Maroc",
        "mq": "Martinique",
        "mu": "Maurice",
        "mr": "Mauritanie",
        "yt": "Mayotte",
        "mx": "Mexique",
        "md": "Moldavie",
        "mc": "Monaco",
        "mn": "Mongolie",
        "me": "Monténégro",
        "ms": "Montserrat",
        "mz": "Mozambique",
        "mm": "Myanmar",
        "na": "Namibie",
        "nr": "Nauru",
        "np": "Népal",
        "ni": "Nicaragua",
        "ne": "Niger",
        "ng": "Nigéria",
        "nu": "Niue",
        "no": "Norvège",
        "nc": "Nouvelle-Calédonie",
        "nz": "Nouvelle-Zélande",
        "om": "Oman",
        "ug": "Ouganda",
        "uz": "Ouzbékistan",
        "pk": "Pakistan",
        "pw": "Palaos",
        "pa": "Panama",
        "pg": "Papouasie-Nouvelle-Guinée",
        "py": "Paraguay",
        "nl": "Pays-Bas",
        "bq": "Pays-Bas caribéens",
        "pe": "Pérou",
        "ph": "Philippines",
        "pl": "Pologne",
        "pf": "Polynésie française",
        "pr": "Porto Rico",
        "pt": "Portugal",
        "qa": "Qatar",
        "hk": "R.A.S. chinoise de Hong Kong",
        "mo": "R.A.S. chinoise de Macao",
        "cf": "République centrafricaine",
        "do": "République dominicaine",
        "ro": "Roumanie",
        "gb": "Royaume-Uni",
        "ru": "Russie",
        "rw": "Rwanda",
        "eh": "Sahara occidental",
        "bl": "Saint-Barthélemy",
        "kn": "Saint-Christophe-et-Niévès",
        "sm": "Saint-Marin",
        "mf": "Saint-Martin",
        "sx": "Saint-Martin",
        "pm": "Saint-Pierre-et-Miquelon",
        "vc": "Saint-Vincent-et-les-Grenadines",
        "sh": "Sainte-Hélène",
        "lc": "Sainte-Lucie",
        "sv": "Salvador",
        "ws": "Samoa",
        "as": "Samoa américaines",
        "st": "Sao Tomé-et-Principe",
        "sn": "Sénégal",
        "rs": "Serbie",
        "sc": "Seychelles",
        "sl": "Sierra Leone",
        "sg": "Singapour",
        "sk": "Slovaquie",
        "si": "Slovénie",
        "so": "Somalie",
        "sd": "Soudan",
        "ss": "Soudan du Sud",
        "lk": "Sri Lanka",
        "se": "Suède",
        "ch": "Suisse",
        "sr": "Suriname",
        "sj": "Svalbard et Jan Mayen",
        "sy": "Syrie",
        "tj": "Tadjikistan",
        "tw": "Taïwan",
        "tz": "Tanzanie",
        "td": "Tchad",
        "cz": "Tchéquie",
        "tf": "Terres australes françaises",
        "io": "Territoire britannique de l’océan Indien",
        "ps": "Territoires palestiniens",
        "th": "Thaïlande",
        "tl": "Timor oriental",
        "tg": "Togo",
        "tk": "Tokelau",
        "to": "Tonga",
        "tt": "Trinité-et-Tobago",
        "ta": "Tristan da Cunha",
        "tn": "Tunisie",
        "tm": "Turkménistan",
        "tr": "Turquie",
        "tv": "Tuvalu",
        "ua": "Ukraine",
        "uy": "Uruguay",
        "vu": "Vanuatu",
        "ve": "Venezuela",
        "vn": "Vietnam",
        "wf": "Wallis-et-Futuna",
        "ye": "Yémen",
        "zm": "Zambie",
        "zw": "Zimbabwe"
    }
} 
