sequenceDiagram
    participant User
    participant Frontend
    participant Backend
    participant IBM Verify
    
    User->>Frontend: User enters registration details
    Frontend->>Backend: POST /api/auth/signup
    Backend->>IBM Verify: /oauth2/token
    IBM Verify-->>Backend:Admin token
    Backend->>IBM Verify:POST /v2.0/Users
    IBM Verify-->>Backend: User created userid (str) and username
    Backend->>IBM Verify: POST factors/emailotp/transient/verifications to email passcode to user
    IBM Verify -->> User: Email passcode to user
    User ->> Frontend: user sends passcode to frontend
    Frontend ->> Backend: POST(URL TBD)
    Backend ->> IBM Verify: POST v2.0/factors/emailotp/{id}/verifications/{trxnId} (body contains passcode and other info)
    IBM Verify -->> Backend: Verify sends HTTP 204 code - The supplied one-time password was successfully verified.
    Backend ->> IBM Verify: POST /v2.0/factors/emailotp (enroll user into accessing email OTPs)
    Backend -->> IBM Verify: POST /v2.0/factors/smsotp (enroll user into accessing SMS OTPs)
    IBM Verify ->> Backend : Backend receives prior verifications
    Backend -->> IBM Verify: POST v2.0/factors/smsotp/transient/verifications to SMS passcode to user
    IBM Verify ->> User : SMS passcode to user
    User ->> Frontend: User sends passcode to frontend
    Frontend ->> Backend:  POST(URL TBD)
    Backend->>IBM Verify: POST /v2.0/factors/smsotp/transient/verifications/{trxnId} (body contains passcode and other info)
    IBM Verify -->> Backend: Verify sends HTTP 204 code - the supplied one-time password was successfully verified.
    Backend -->> Frontend: Frontend acknowledges success