graph TB
    subgraph "AWS Cloud - GC Sign In (Region: ca-central-1)"
        subgraph "VPC"
            subgraph "Public Subnet"
                ALB[Application Load Balancer]
                WAF[AWS WAF]
            end

            subgraph "Private Subnet"
                subgraph "ECS Cluster"
                    subgraph "Backend Container"
                        APIProxy["API Proxy (FastAPI)"]
                        APIClient["IBM Verify API Client"]
                    end
                end

            end
        end

        subgraph "Security & Monitoring"
            CloudWatch[CloudWatch]
            SecretsManager[Secrets Manager]
        end

        subgraph "CloudFront Edge"
            CloudFront[CloudFront]
            CFWAF[AWS WAF]
        end

        Route53["Route 53 (DNS)"]
        S3[S3 Bucket<br/>Front-end Web assets]
    end

    subgraph "External Services"
        IBMVerify["IBM Security Verify<br/>(CIAM)"]
    end

    RelyingParty[Relying Party]
    WebBrowser["Users (Web Browser)"]

    %% Connections
    WebBrowser -->|HTTPS| CloudFront
    WebBrowser -->|"API Calls<br/>HTTPS"| ALB
    CloudFront -->|Static Content| S3
    WAF -.->|Protect| ALB
    CFWAF -.->|Protect| CloudFront
    ALB -->|API Requests| APIProxy
    APIClient -->|Signin+Signup+Profile HTTPS| IBMVerify
    APIClient -->|Secrets| SecretsManager
    RelyingParty-->|"OIDC endpoints<br/>HTTPS"| IBMVerify
    RelyingParty-->|"Redirect (authorize)<br/>HTTPS"| WebBrowser
    WebBrowser-->|"Redirect (callback)<br/>HTTPS"| RelyingParty
    APIProxy-->|Uses| APIClient

    %% Monitoring
    WAF -.->|Logs| CloudWatch
    APIProxy -.->|Logs| CloudWatch