sequenceDiagram
    participant enduser
    participant gc-signin-ibm (backend)
    participant ibm verify api
    enduser->>gc-signin-ibm (backend): user's OIDC sent to backend's login endpoint   
    gc-signin-ibm (backend)->>ibm verify api: makes request for fresh jwt
    ibm verify api->>gc-signin-ibm (backend): login response
    gc-signin-ibm (backend)->>enduser: forwards login response to enduser