name: "Frontend Lint"
on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-lint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: frontend

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: "Install Node"
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20.x"

      - name: "Install Deps"
        working-directory: ${{ matrix.module }}
        run: npm install

      - name: "ESLint"
        working-directory: ${{ matrix.module }}
        run: npm run lint
