name: "Frontend Code Coverage"
on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-code-coverage.yml"
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-code-coverage.yml"

jobs:
  vite-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: frontend

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: "Install Node"
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: "Install Deps"
        working-directory: ${{ matrix.module }}
        run: npm ci

      - name: "Cache Playwright browsers"
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('frontend/package-lock.json') }}

      - name: "Install Playwright Browsers"
        working-directory: ${{ matrix.module }}
        run: npx playwright install --with-deps chromium
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: "Run Vitest Code Coverage"
        working-directory: ${{ matrix.module }}
        run: npm run test

      - name: "Upload Coverage"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: frontend-coverage-report
          path: ${{ matrix.module }}

  report-coverage:
    permissions:
      contents: read
      pull-requests: write
    needs: vite-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: frontend
    steps:
      - name: "Download Coverage Artifacts"
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: frontend-coverage-report
          path: ${{ matrix.module }}

      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@5b6122e3a819a3be7b27fc961b7faafb3bf00e4d # v2.9.0
        with:
          vite-config-path: "./vitest.config.js"
          working-directory: "./${{ matrix.module }}"
