on:
  push:
    branches:
      - main
  workflow_dispatch: # Added for ease of debugging for now.

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

env:
  AWS_REGION: ca-central-1
  GITHUB_SHA: ${{ github.sha }}
  SBOM_TAG_NAME: gc-signin-dev-backend-api
  SLACK_NOTIFICATION_APPLICATION_NAME: "GC Sign-In Manage Application"

name: Release Pipeline - Frontend & Backend API

jobs:
  # Runs the release-please action. This manages the open release PR and
  # creates the release when the PR is merged.
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: sre_app_token
        with:
          app-id: ${{ secrets.CDS_RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.CDS_RELEASE_BOT_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release
        with:
          token: ${{ steps.sre_app_token.outputs.token }}

  notify-slack-about-deploy:
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.check-envs.outputs.envs }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check what environments are being deployed to
        id: check-envs
        if: github.event_name != 'workflow_dispatch'
        run: |
          ENVS_TO_DEPLOY=""
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            if [[ "$file" == .deployed_versions/*.json ]]; then
              ENV_NAME=$(basename $file .json)
              if [ -z "$ENVS_TO_DEPLOY" ]; then
                ENVS_TO_DEPLOY="$ENV_NAME"
              else
                ENVS_TO_DEPLOY="$ENVS_TO_DEPLOY,$ENV_NAME"
              fi
            fi
          done
          echo "Found environments to deploy: $ENVS_TO_DEPLOY"
          echo "envs=$ENVS_TO_DEPLOY" >> $GITHUB_OUTPUT

      - name: Notify slack
        if: steps.check-envs.outputs.envs != ''
        run: |
          workflow_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          json='{"text":":hourglass: '"${{ env.SLACK_NOTIFICATION_APPLICATION_NAME }}"' is being deployed to the following environments: `'"${{ steps.check-envs.outputs.envs }}"'`\n\n<'"$workflow_url"'|Click for more details>"}'

          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.GC_SIGNIN_OPS_SLACK_INFO_WEBHOOK }}

  # Builds the frontend application for the current SHA and stores the artifact in S3.
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test, staging]
    environment: ${{ matrix.environment }}
    needs: notify-slack-about-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "latest"

      - name: configure aws credentials using OIDC role
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID}}:role/github_action_push_S3
          role-session-name: GHPushAppS3
          aws-region: ${{ env.AWS_REGION }}

      - name: Environment Variables for build
        run: |
          echo "VITE_BACKEND_API_URL=${{ secrets.VITE_BACKEND_API_URL }}" >> $GITHUB_ENV
          echo "VITE_GOOGLE_ANALYTICS_ID=${{ secrets.VITE_GOOGLE_ANALYTICS_ID }}" >> $GITHUB_ENV

      - name: Build application
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Upload build artifacts to S3
        run: |
          aws s3 sync frontend/dist s3://${{ secrets.FRONTEND_APP_BUILD_ARTIFACTS_S3_BUCKET }}/${GITHUB_SHA}

  # Builds the backend application for the current SHA and stores the artifact in ECR.
  build-backend:
    runs-on: ubuntu-latest
    environment: dev
    needs: notify-slack-about-deploy
    steps:
      - name: Audit DNS requests
        uses: cds-snc/dns-proxy-action@main
        env:
          DNS_PROXY_FORWARDTOSENTINEL: "true"
          DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
          DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

      - name: configure aws credentials using OIDC role
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github_action_manage_push_ecr_ecs
          role-session-name: ECRPush
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Build Docker image
        working-directory: ./backend/
        run: |
          docker build \
          --tag ${{ vars.ARTIFACT_ECR_REPOSITORY }}:$GITHUB_SHA .

      - name: Push Container to Amazon ECR
        working-directory: ./backend/
        run: |
          docker push ${{ vars.ARTIFACT_ECR_REPOSITORY }}:$GITHUB_SHA

      - name: Docker generate SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@34794baf2af592913bb5b51d8df4f8d0acc49b6f # v3.2.0
        env:
          TRIVY_DB_REPOSITORY: ${{ vars.TRIVY_DB_REPOSITORY }}
        with:
          docker_image: "${{ vars.ARTIFACT_ECR_REPOSITORY }}:${{ env.GITHUB_SHA }}"
          dockerfile_path: backend/Dockerfile
          sbom_name: ${{ env.SBOM_TAG_NAME }}
          token: "${{ secrets.GITHUB_TOKEN }}"

  # Deploys frontend application to necessary environments.
  # We check the current SHA deployed to the environment to only deploy if necessary.
  deploy-frontends:
    needs: [release-please, build-frontend]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test, staging]
    environment: ${{ matrix.environment }}
    steps:
      - run: echo "Deploying frontend to ${{ matrix.environment }} environment..."

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      # Set the SHA to use for the deployment.
      # In `dev`, we always use the main sha (the SHA this workflow is running for).
      # In all other environments, we need to resolve the tag in ./deployed_versions/{env}.json["version"]
      - name: Set deployment SHA
        run: |
          if [ "${{ matrix.environment }}" = "dev" ]; then
            echo "DEPLOYMENT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          else
            DEPLOYMENT_TAG=$(cat .deployed_versions/${{ matrix.environment }}.json | jq -r '.version')
            DEPLOYMENT_SHA=$(git rev-list -n 1 v$DEPLOYMENT_TAG)
            echo "DEPLOYMENT_SHA=${DEPLOYMENT_SHA}" >> $GITHUB_ENV
          fi

      - name: Output deployment SHA
        run: echo "Deployment SHA is ${DEPLOYMENT_SHA}"

      - name: Ensure deployment SHA is set
        run: |
          if [ -z "${DEPLOYMENT_SHA}" ]; then
            echo "DEPLOYMENT_SHA is not set. Exiting."
            exit 1
          fi

      - name: configure aws credentials using OIDC role
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID}}:role/github_action_push_S3
          role-session-name: GHPushAppS3
          aws-region: ${{ env.AWS_REGION }}

      - name: Ensure deployment build exists
        run: |
          if ! aws s3 ls s3://${{ secrets.FRONTEND_APP_BUILD_ARTIFACTS_S3_BUCKET }}/${DEPLOYMENT_SHA}/ ; then
            echo "No build artifacts found for SHA ${DEPLOYMENT_SHA} in bucket ${{ secrets.FRONTEND_APP_BUILD_ARTIFACTS_S3_BUCKET }}. Exiting."
            exit 1
          fi

      - name: Deploy build to app bucket
        run: |
          aws s3 sync \
            s3://${{ secrets.FRONTEND_APP_BUILD_ARTIFACTS_S3_BUCKET }}/$DEPLOYMENT_SHA \
            s3://${{ secrets.FRONTEND_APP_S3_BUCKET }}

      - name: Invalidate FRONTEND_APP_CLOUDFRONT_DISTRIBUTION cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.FRONTEND_APP_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/index.html"

  # Deploys backend application to necessary environments.
  # We check the current SHA deployed to the environment to only deploy if necessary.
  deploy-backends:
    needs: [release-please, build-backend]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test, staging]
    environment: ${{ matrix.environment }}
    steps:
      - run: echo "Deploying backend to ${{ matrix.environment }} environment..."

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      # Set the SHA to use for the deployment.
      # In `dev`, we always use the main sha (the SHA this workflow is running for).
      # In all other environments, we need to resolve the tag in ./deployed_versions/{env}.json["version"]
      - name: Set deployment SHA
        run: |
          if [ "${{ matrix.environment }}" = "dev" ]; then
            echo "DEPLOYMENT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          else
            DEPLOYMENT_TAG=$(cat .deployed_versions/${{ matrix.environment }}.json | jq -r '.version')
            DEPLOYMENT_SHA=$(git rev-list -n 1 v$DEPLOYMENT_TAG)
            echo "DEPLOYMENT_SHA=${DEPLOYMENT_SHA}" >> $GITHUB_ENV
          fi

      - name: Output deployment SHA
        run: echo "Deployment SHA is ${DEPLOYMENT_SHA}"

      - name: Ensure deployment SHA is set
        run: |
          if [ -z "${DEPLOYMENT_SHA}" ]; then
            echo "DEPLOYMENT_SHA is not set. Exiting."
            exit 1
          fi

      - name: configure aws credentials using OIDC role
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github_action_manage_push_ecr_ecs
          role-session-name: ECRPush
          aws-region: ${{ env.AWS_REGION }}

      - name: Get current service definition
        id: current-service-def
        run: |
          CURRENT_TASK_DEF_ARN=$(aws ecs describe-services \
            --cluster ${{ vars.ECS_CLUSTER }} \
            --services ${{ vars.ECS_SERVICE }} \
            --query "services[0].taskDefinition" \
            --output text)

          echo "CURRENT_TASK_DEF_ARN=$CURRENT_TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Get current image
        id: current-image
        run: |
          CURRENT_IMAGE=$(aws ecs describe-task-definition \
            --task-definition ${{ env.CURRENT_TASK_DEF_ARN }} \
            --query "taskDefinition.containerDefinitions[?name=='${{ vars.ECS_SERVICE }}'].image" \
            --output text)
            
          echo "CURRENT_IMAGE=$CURRENT_IMAGE" >> $GITHUB_ENV
          echo "Current image is $CURRENT_IMAGE"

      - name: Check if deployment is needed
        id: check-deployment-needed
        run: |
          if [ "$CURRENT_IMAGE" = "${{ vars.ARTIFACT_ECR_REPOSITORY }}:${{ env.DEPLOYMENT_SHA }}" ]; then
            echo "Current image is the same as deployment image. No deployment needed."
            echo "deployment_needed=false" >> $GITHUB_OUTPUT
          else
            echo "Deployment needed."
            echo "deployment_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Download ECS task definition
        if: steps.check-deployment-needed.outputs.deployment_needed == 'true'
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ vars.ECS_SERVICE }} \
            --query taskDefinition > task-definition.json

      - name: Update ECS task image
        if: steps.check-deployment-needed.outputs.deployment_needed == 'true'
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@5cb8c74c1b1ecaec4c8ea82eff82c009333509ce # v1.8.0
        with:
          task-definition: task-definition.json
          container-name: ${{ vars.ECS_SERVICE }}
          image: ${{ vars.ARTIFACT_ECR_REPOSITORY }}:${{ env.DEPLOYMENT_SHA }}

      - name: Deploy updated ECS task
        if: steps.check-deployment-needed.outputs.deployment_needed == 'true'
        uses: aws-actions/amazon-ecs-deploy-task-definition@1beffbdddb3eb5f83c7a746c3e9bafeccdccbbaa # v2.4.0
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ vars.ECS_SERVICE }}
          cluster: ${{ vars.ECS_CLUSTER }}
          wait-for-service-stability: true
          propagate-tags: SERVICE

  notify-slack-about-deploy-success:
    runs-on: ubuntu-latest
    needs: [notify-slack-about-deploy, deploy-frontends, deploy-backends]
    if: success() && needs.notify-slack-about-deploy.outputs.envs != ''
    steps:
      - name: Notify slack about successful Deployments
        run: |
          workflow_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          json='{"text":":white_check_mark: '"${{ env.SLACK_NOTIFICATION_APPLICATION_NAME }}"' has been successfully deployed to the following environments: `'"${{ needs.notify-slack-about-deploy.outputs.envs }}"'`!\n\n<'"$workflow_url"'|Click for more details>"}'

          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.GC_SIGNIN_OPS_SLACK_INFO_WEBHOOK }}

  notify-slack-about-deploy-failure:
    runs-on: ubuntu-latest
    needs: [notify-slack-about-deploy, deploy-frontends, deploy-backends]
    if: failure() && needs.notify-slack-about-deploy.outputs.envs != ''
    steps:
      - name: Notify slack about failed Deployments
        run: |
          workflow_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          json='{"text":":x: '"${{ env.SLACK_NOTIFICATION_APPLICATION_NAME }}"' FAILED to deploy to the following environments: `'"${{ needs.notify-slack-about-deploy.outputs.envs }}"'`!\n\n<'"$workflow_url"'|Click for more details>"}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.GC_SIGNIN_OPS_SLACK_ALERT_WEBHOOK }}
