on:
  push:
    branches:
      - main
  workflow_dispatch: # Added for ease of debugging for now.

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

env:
  AWS_REGION: ca-central-1
  GITHUB_SHA: ${{ github.sha }}

name: release-pipeline

jobs:
  # Runs the release-please action. This manages the open release PR and
  # creates the release when the PR is merged.
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: sre_app_token
        with:
          app-id: ${{ secrets.CDS_RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.CDS_RELEASE_BOT_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release
        with:
          token: ${{ steps.sre_app_token.outputs.token }}

  # Builds the frontend application for the current SHA and stores the artifact in S3.
  build-frontend:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "latest"

      - name: configure aws credentials using OIDC role
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID}}:role/github_action_push_S3
          role-session-name: GHPushAppS3
          aws-region: ${{ env.AWS_REGION }}

      - name: Environment Variables for build
        run: |
          echo "VITE_BACKEND_API_URL=${{ secrets.VITE_BACKEND_API_URL }}" >> $GITHUB_ENV
          echo "VITE_GOOGLE_ANALYTICS_ID=${{ secrets.VITE_GOOGLE_ANALYTICS_ID }}" >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Upload build artifacts to S3
        run: |
          aws s3 sync frontend/dist s3://${{ secrets.FRONTEND_APP_BUILD_ARTIFACTS_S3_BUCKET }}/${GITHUB_SHA}

  # Builds the backend application for the current SHA and stores the artifact in ECR.
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building backend..."

  # Deploys frontend application to necessary environments.
  # We check the current SHA deployed to the environment to only deploy if necessary.
  deploy-frontends:
    needs: [release-please, build-frontend]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test]
    environment: ${{ matrix.environment }}
    steps:
      - run: echo "Deploying frontend to ${{ matrix.environment }} environment..."

  # Deploys backend application to necessary environments.
  # We check the current SHA deployed to the environment to only deploy if necessary.
  deploy-backends:
    needs: [release-please, build-backend]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test]
    environment: ${{ matrix.environment }}
    steps:
      - run: echo "Deploying backend to ${{ matrix.environment }} environment..."
